[0m16:48:13.480339 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cffa90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108664880>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086648b0>]}


============================== 16:48:13.483250 | 67ee2bc1-e2a2-4584-9da6-91b75980c33a ==============================
[0m16:48:13.483250 [info ] [MainThread]: Running with dbt=1.5.1
[0m16:48:13.483566 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/sean.odriscoll/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m16:49:04.117616 [debug] [MainThread]: Starter project path: /opt/homebrew/Cellar/dbt-bigquery/1.5.1/libexec/lib/python3.9/site-packages/dbt/include/starter_project
[0m16:49:09.516335 [debug] [MainThread]: Command `dbt init` succeeded at 16:49:09.515942 after 56.06 seconds
[0m16:49:09.518075 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106cffa90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086b49a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1086b46d0>]}
[0m16:49:09.518752 [debug] [MainThread]: Flushing usage events
[0m16:49:19.719771 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c6f490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118394940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118394910>]}


============================== 16:49:19.722402 | 15de59c3-26c3-479a-82e5-f376f794eaa7 ==============================
[0m16:49:19.722402 [info ] [MainThread]: Running with dbt=1.5.1
[0m16:49:19.722744 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/sean.odriscoll/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m16:49:25.895829 [error] [MainThread]: Encountered an error:

[0m16:49:25.900453 [error] [MainThread]: Traceback (most recent call last):
  File "/opt/homebrew/Cellar/dbt-bigquery/1.5.1/libexec/lib/python3.9/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/dbt-bigquery/1.5.1/libexec/lib/python3.9/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/dbt-bigquery/1.5.1/libexec/lib/python3.9/site-packages/dbt/cli/main.py", line 457, in init
    results = task.run()
  File "/opt/homebrew/Cellar/dbt-bigquery/1.5.1/libexec/lib/python3.9/site-packages/dbt/task/init.py", line 286, in run
    project_name = self.get_valid_project_name()
  File "/opt/homebrew/Cellar/dbt-bigquery/1.5.1/libexec/lib/python3.9/site-packages/dbt/task/init.py", line 243, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
  File "/opt/homebrew/Cellar/dbt-bigquery/1.5.1/libexec/lib/python3.9/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/opt/homebrew/Cellar/dbt-bigquery/1.5.1/libexec/lib/python3.9/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m16:49:25.902131 [debug] [MainThread]: Command `dbt init` failed at 16:49:25.901944 after 6.20 seconds
[0m16:49:25.902976 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c6f490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118394d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118394ee0>]}
[0m16:49:25.903465 [debug] [MainThread]: Flushing usage events
